In [ ]:
# Comment test to Git

In [45]:
# Libraries
import os
import mne
import pandas as pd
import matplotlib.pyplot as plt

# 1. Define the path to the .vhdr file

In [46]:
FolderPath = "C:\\Users\\indira.lavocat\\MOVIDOC\\EEG\\Sujets\\IndiraLAVOCAT" # need to adapt the last folder to suit the subject

# Looking for the .vhdr file in the folder
for file in os.listdir(FolderPath):
    if file.endswith(".vhdr"):
        FilePath = os.path.join(FolderPath, file)
        break

print(FilePath)


# vhdr_file = "C:\\Users\\indira.lavocat\\MOVIDOC\\EEG\\Indira Test\\MOVIDOCTicTrack000005.vhdr"

C:\Users\indira.lavocat\MOVIDOC\EEG\Sujets\IndiraLAVOCAT\MOVIDOCTicTrack000005.vhdr


# 2. Load the data

In [47]:
raw = mne.io.read_raw_brainvision(FilePath, preload=True)

Extracting parameters from C:\Users\indira.lavocat\MOVIDOC\EEG\Sujets\IndiraLAVOCAT\MOVIDOCTicTrack000005.vhdr...
Setting channel info structure...
Reading 0 ... 79759  =      0.000 ...   159.518 secs...


C:\Users\indira.lavocat\AppData\Local\Temp\ipykernel_6364\2402428994.py:1: RuntimeWarning: Online software filter detected. Using software filter settings and ignoring hardware values
  raw = mne.io.read_raw_brainvision(FilePath, preload=True)


In [48]:
raw.info

<Info | 7 non-empty values
 bads: []
 ch_names: Fp1, F3, F7, FT9, FC5, FC1, C3, T7, TP9, CP5, CP1, Pz, P3, P7, ...
 chs: 31 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 250.0 Hz
 meas_date: 2025-05-13 16:30:12 UTC
 nchan: 31
 projs: []
 sfreq: 500.0 Hz
>

In [49]:
# raw.ch_names
print(raw.ch_names)


['Fp1', 'F3', 'F7', 'FT9', 'FC5', 'FC1', 'C3', 'T7', 'TP9', 'CP5', 'CP1', 'Pz', 'P3', 'P7', 'O1', 'Oz', 'O2', 'P4', 'P8', 'TP10', 'CP6', 'CP2', 'Cz', 'C4', 'T8', 'FT10', 'FC6', 'FC2', 'F4', 'F8', 'Fp2']


In [50]:
print(raw.info['description']) # gives a note about the channels when there is one

None


## Obtain the stimulus

In [51]:
# Create an event dicionnary
events, event_id = mne.events_from_annotations(raw)
print("Events list (stimulus) :")
print(event_id)

Used Annotations descriptions: [np.str_('New Segment/'), np.str_('Stimulus/S  1'), np.str_('Stimulus/S  2'), np.str_('Stimulus/S  3'), np.str_('Stimulus/S  4'), np.str_('Stimulus/S  5'), np.str_('Stimulus/S  6'), np.str_('Stimulus/S  7'), np.str_('Stimulus/S  8'), np.str_('Stimulus/S  9'), np.str_('Stimulus/S 10'), np.str_('Stimulus/S 11'), np.str_('Stimulus/S 12'), np.str_('Stimulus/S 13'), np.str_('Stimulus/S 14'), np.str_('Stimulus/S 21'), np.str_('Stimulus/S 22'), np.str_('Stimulus/S 23'), np.str_('Stimulus/S 24'), np.str_('Stimulus/S 25')]
Events list (stimulus) :
{np.str_('New Segment/'): 99999, np.str_('Stimulus/S  1'): 1, np.str_('Stimulus/S  2'): 2, np.str_('Stimulus/S  3'): 3, np.str_('Stimulus/S  4'): 4, np.str_('Stimulus/S  5'): 5, np.str_('Stimulus/S  6'): 6, np.str_('Stimulus/S  7'): 7, np.str_('Stimulus/S  8'): 8, np.str_('Stimulus/S  9'): 9, np.str_('Stimulus/S 10'): 10, np.str_('Stimulus/S 11'): 11, np.str_('Stimulus/S 12'): 12, np.str_('Stimulus/S 13'): 13, np.str_('S

In [52]:
# Display the tab of events
print("Events (sample, previous_id, event_id) :")
print(events)

Events (sample, previous_id, event_id) :
[[    0     0 99999]
 [ 2971     0     1]
 [ 6388     0    25]
 [ 6393     0     2]
 [10935     0    25]
 [10940     0     3]
 [12636     0    21]
 [13521     0    21]
 [14309     0    21]
 [15058     0    21]
 [15773     0    21]
 [15777     0     4]
 [19459     0    25]
 [19464     0     5]
 [24943     0     6]
 [28263     0    25]
 [28267     0     7]
 [33753     0     8]
 [36571     0    25]
 [36575     0     9]
 [38181     0    21]
 [38568     0    22]
 [40526     0    21]
 [41150     0    22]
 [42979     0    21]
 [43429     0    22]
 [44578     0    21]
 [45201     0    22]
 [46138     0    21]
 [46350     0    22]
 [47052     0    10]
 [51114     0    25]
 [51119     0    11]
 [51765     0    21]
 [52266     0    22]
 [54178     0    21]
 [54709     0    22]
 [55872     0    21]
 [56340     0    22]
 [57552     0    21]
 [58051     0    22]
 [59551     0    24]
 [60448     0    24]
 [61248     0    21]
 [61731     0    22]
 [61776     0 

In [53]:
# Convert the timestamps into seconds
events_times_sec = events[:, 0] / raw.info['sfreq'] # converts the timestamps into seconds

for time, eid in zip(events_times_sec, events[:, 2]): # links each time in seconds to its event ID
    print(f"Stimulus {eid} à {time:.3f} s") # formats the number with 3 decimal

Stimulus 99999 à 0.000 s
Stimulus 1 à 5.942 s
Stimulus 25 à 12.776 s
Stimulus 2 à 12.786 s
Stimulus 25 à 21.870 s
Stimulus 3 à 21.880 s
Stimulus 21 à 25.272 s
Stimulus 21 à 27.042 s
Stimulus 21 à 28.618 s
Stimulus 21 à 30.116 s
Stimulus 21 à 31.546 s
Stimulus 4 à 31.554 s
Stimulus 25 à 38.918 s
Stimulus 5 à 38.928 s
Stimulus 6 à 49.886 s
Stimulus 25 à 56.526 s
Stimulus 7 à 56.534 s
Stimulus 8 à 67.506 s
Stimulus 25 à 73.142 s
Stimulus 9 à 73.150 s
Stimulus 21 à 76.362 s
Stimulus 22 à 77.136 s
Stimulus 21 à 81.052 s
Stimulus 22 à 82.300 s
Stimulus 21 à 85.958 s
Stimulus 22 à 86.858 s
Stimulus 21 à 89.156 s
Stimulus 22 à 90.402 s
Stimulus 21 à 92.276 s
Stimulus 22 à 92.700 s
Stimulus 10 à 94.104 s
Stimulus 25 à 102.228 s
Stimulus 11 à 102.238 s
Stimulus 21 à 103.530 s
Stimulus 22 à 104.532 s
Stimulus 21 à 108.356 s
Stimulus 22 à 109.418 s
Stimulus 21 à 111.744 s
Stimulus 22 à 112.680 s
Stimulus 21 à 115.104 s
Stimulus 22 à 116.102 s
Stimulus 24 à 119.102 s
Stimulus 24 à 120.896 s
Stimulu

### Alternative to display the stimulus name (and not its ID) with its timestamp in seconds

In [44]:
id_to_name = {v: k for k, v in event_id.items()}

for time, eid in zip(events_times_sec, events[:, 2]):
    name = id_to_name.get(eid, f"ID {eid}")
    print(f"{name} à {time:.3f} s")

New Segment/ à 0.000 s
Stimulus/S  1 à 5.942 s
Stimulus/S 25 à 12.776 s
Stimulus/S  2 à 12.786 s
Stimulus/S 25 à 21.870 s
Stimulus/S  3 à 21.880 s
Stimulus/S 21 à 25.272 s
Stimulus/S 21 à 27.042 s
Stimulus/S 21 à 28.618 s
Stimulus/S 21 à 30.116 s
Stimulus/S 21 à 31.546 s
Stimulus/S  4 à 31.554 s
Stimulus/S 25 à 38.918 s
Stimulus/S  5 à 38.928 s
Stimulus/S  6 à 49.886 s
Stimulus/S 25 à 56.526 s
Stimulus/S  7 à 56.534 s
Stimulus/S  8 à 67.506 s
Stimulus/S 25 à 73.142 s
Stimulus/S  9 à 73.150 s
Stimulus/S 21 à 76.362 s
Stimulus/S 22 à 77.136 s
Stimulus/S 21 à 81.052 s
Stimulus/S 22 à 82.300 s
Stimulus/S 21 à 85.958 s
Stimulus/S 22 à 86.858 s
Stimulus/S 21 à 89.156 s
Stimulus/S 22 à 90.402 s
Stimulus/S 21 à 92.276 s
Stimulus/S 22 à 92.700 s
Stimulus/S 10 à 94.104 s
Stimulus/S 25 à 102.228 s
Stimulus/S 11 à 102.238 s
Stimulus/S 21 à 103.530 s
Stimulus/S 22 à 104.532 s
Stimulus/S 21 à 108.356 s
Stimulus/S 22 à 109.418 s
Stimulus/S 21 à 111.744 s
Stimulus/S 22 à 112.680 s
Stimulus/S 21 à 115.

### Alternative whith a pandas DataFrame output

In [ ]:
id_to_name = {v: k for k, v in event_id.items()}

events_data = [] # création of dictionnaries list (one per event)
for time, eid in zip(events_times_sec, events[:, 2]):
    name = id_to_name.get(eid, f"ID {eid}")
    events_data.append({
        "Nom de l'événement": name,
        "ID": eid,
        "Temps (s)": round(time, 3)
    })

df_events = pd.DataFrame(events_data) # conversion into a DataFrame

print(df_events)

# 3. Define the montage ???

In [ ]:
raw.set_montage("standard_1020") # to prevent any error during the topography steps
fig1 = raw.plot_sensors(show_names=True)

# 4. Plot the data

In [ ]:
Original_Signal_Figure_1 = raw.plot(title = "Orginal Signal")
raw.info
raw.ch_names
print(raw)

# raw.plot(duration=5, n_channels=30)
# raw.compute_psd(fmax=50).plot(picks="data", exclude="bads", amplitude=False)

# 5. Extract the events (from the .vmrk annotations)

In [ ]:
events, event_id = mne.events_from_annotations(raw)
print("Événements détectés :", event_id)

# 5. OPTION

In [ ]:
print(events)

In [ ]:
print(raw.annotations)

In [ ]:
events, event_id = mne.events_from_annotations(raw)
print("Événements détectés :", event_id)

In [ ]:
print(raw.times[0], raw.times[-1])
print(raw.times[-1] - raw.times[0])

# 4. Filter the data

In [ ]:
raw.filter(l_freq=1., h_freq=30.) # for ERPs, [1-30] Hz band-pass filter

# 6. Seperation in epochs

In [ ]:
tmin = -0.2  # 200 ms before the event
tmax = 0.8   # 800 ms after the event
epochs = mne.Epochs(raw, events, event_id=event_id,
                    tmin=tmin, tmax=tmax, baseline=(None, 0),
                    preload=True)
epochs.plot_drop_log()

# 7. Define an automatic reject of the artifacts (optional)

In [ ]:
# epochs.plot_drop_log()
# epochs.drop_bad()

# 8. Averaging (ERP)

In [ ]:
evoked = epochs.average()
# evoked.plot(title="ERP (moyenne des epochs)")
evoked.plot() # evoked does not accept any "title"

# To add a title to the graph
# fig = evoked.plot_image(picks='eeg')
# fig.suptitle("ERP (moyenne des epochs)")


In [ ]:
# To add a title to the graph
fig = evoked.plot_image(picks='eeg')
fig.suptitle("ERP (moyenne des epochs)")

# 9. Topography

In [ ]:
# evoked.plot_topomap(times=[0.1, 0.2, 0.3], ch_type='eeg', title="Topomap à 100/200/300 ms")
evoked.plot_topomap(times=[0.1, 0.2, 0.3], ch_type='eeg')

*** Show the Data ***

In [ ]:
plt.show()